#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 14 17:55:22 2019

@author: cherrie
"""

# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


############Please fill in the blank functions to run the whole program#######
def get_stock_data(path, columns=None):
    """
    :param path: path to the .csv file containing stock information
    :param columns: the columns from the original dataframe to be returned, if None return all data
    :return:
    """
    print("Retrieving Data...")
    df = pd.read_csv(path)
    df = df.set_index('Date')
    if columns is None:
        return df
    else:
        return df[columns]


def get_daily_return(df_adj_close):
    """
    :param df_adj_close: pandas series data that contains the adjusted close price of an asset
    :return: the mean and standard deviation as implied in the df_adj_close
    """

    ####### Fill this function to return the daily return mean and std########
    print("Calculating mean and standard deviation...")
    sp_daily = df_adj_close.pct_change()
    sp_daily = sp_daily.dropna()
    mean = sp_daily.mean()
    print(mean)
    std = sp_daily.std()
    print(std)

    ##########################################################################
    return mean, std


def simulate_stock_price(df_adj_close, num_simulations=50):
    """
    :param df_adj_close: pandas series object that contains the adjusted close price
    :param num_simulations: number of simulations to be generated
    :return: df_simulation: the simulated close price dataframe
             df_mean: the dataframe containing the price series should the stock has not volatility and daily return
                      equals the expected daily return implied in df_adj_close
    """
    mean, std = get_daily_return(df_adj_close)
    s0 = df_adj_close.iloc[0]
    length = len(df_adj_close)-1
    ##### Complete this function for price simulation#################
    print("Simulating...")
    
    r = np.random.randn(length, num_simulations)*std + mean
    cum_r = np.cumprod(1+r, axis=0)
    s = s0 * cum_r
    s = np.insert(s, obj=0, values=s0, axis=0)
    df_simulation = pd.DataFrame(data=s, index=df_adj_close.index)
    mean_return = np.zeros([length]) + mean
    s_mean = s0 * np.cumprod(1+mean_return, axis=0) 
    s_mean = np.insert(s_mean, obj=0, values=s0, axis=0)
    df_mean = pd.DataFrame(data=s_mean, index=df_adj_close.index)


    ###################################################################

    return df_simulation, df_mean


def plot_simulation_with_mean(df_simulation, df_mean, title="Simulation"):
    """
    :param df_simulation: dataframe containing the simulated close price for an asset
    :param df_mean: dataframe containing the mean-return price series for an asset
    :param title: title of the plot, default "Simulation"
    """
    #assert df_simulation.index == df_mean.index
    ##### Complete this function for plot both the simulated price and mean price#################
    print("Plotting simulation...")
    plt.plot(df_simulation)
    plt.plot(df_mean, color='red', linewidth=4, label='Mean Return')
    plt.legend()

    ##############################################################################################
    plt.show()

""""
def plot_volume_data(df_volume, title="Volume"):
    
    :param df_volume: pandas series that contains volume data, indexed by dates
    :param title: title of the plot, default "Volume"
    :return:
    
    ##### Complete this function for plot both the simulated price and mean price#################
    print("Plotting volume data...")
    


    ##############################################################################################
    plt.show()
"""

if __name__ == "__main__":
    np.random.seed(123)
    df_adj_close = get_stock_data('C:/Users/cczq/Desktop/6102/S&P500.csv', columns='Adj Close')
    #df_volume = get_stock_data('/Users/cherrie/Desktop/肖雨晗/master/S&P500.csv', columns='Volume')
    print("Data Retrived")
    df_simulation, df_mean = simulate_stock_price(df_adj_close, num_simulations=100)
    print(df_simulation, df_mean)
    plot_simulation_with_mean(df_simulation, df_mean)
    #plot_volume_data(df_volume)
